[workspace]
resolver = "2"
members = ["cvlr-soroban", "cvlr-soroban-macros", "cvlr-soroban-derive"]

[workspace.package]
version = "0.4.0"
authors = [
    "Arie Gurfinkel <arie@certora.com>",
    "Jorge A. Navas <jorge@certora.com>",
    "Francesco Parolini <francesco@certora.com>",
    "Chandrakana Nandi <chandra@certora.com>",
    "Alexander Bakst <abakst@certora.com>",
]
edition = "2021"
description = "CVLR support for Stellar Soroban smart contracts"
documentation = "https://docs.rs/cvlr-soroban/latest"
license = "MIT"
keywords = [
    "certora", 
    "assert", 
    "soroban", 
    "verification", 
    "formal-methods",
]
categories = [
    "development-tools::debugging", 
    "development-tools::testing", 
    "no-std"
]
readme = "README.md"
homepage = "https://www.certora.com"
repository = "https://github.com/Certora/cvlr-soroban"


[workspace.dependencies]
proc-macro2 = "1"
quote = "1"
syn = "2"
macrotest = "1"
trybuild = "1"
soroban-sdk = { version = "26.1.0", default-features = false }

cvlr-asserts = { git = "https://github.com/Certora/cvlr", branch = "0.6.1-soroban-changes" }
cvlr-nondet = {  git = "https://github.com/Certora/cvlr", branch = "0.6.1-soroban-changes", default-features = false }
cvlr-log = {  git = "https://github.com/Certora/cvlr", branch = "0.6.1-soroban-changes" }
