[package]
name = "cvlr-soroban"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true
authors.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = []
rt = ["cvlr-nondet/rt", "cvlr-asserts/rt"]
testutils = ["soroban-sdk/testutils"]

[dependencies]

soroban-sdk = { workspace = true }

cvlr-asserts = { workspace = true }
cvlr-nondet = { workspace = true, default-features = false }
cvlr-log = { workspace = true, default-features = false }
