[package]
name = "cvlr-soroban-macros"
description = "Macros for cvlr-soroban"
version.workspace = true
edition.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true
authors.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = []

[dependencies]